# -*- coding: utf-8 -*-
"""520.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m94gdb5W3rEMm76Vnapa0WIiDOGBSour
"""

import numpy as np 
import pandas as pd 
import seaborn as sns

iris = sns.load_dataset("iris")

iris.head()

sns.barplot(x="species", y="sepal_length", data=iris)

sns.barplot(x="sepal_length", y="sepal_width",data=iris)

import  pandas  as  pd
df = pd.DataFrame([{ "trajectory_number" :  '1' ,  "trajectory_type" :  "AKI" ,  "crossing_time_in_seconds" :  150 },
{ "trajectory_number" :  '2' ,  "trajectory_type" :  "AKI" ,  "crossing_time_in_seconds" :  800 },
{ "trajectory_number" :  '3' ,  "trajectory_type" :  "AKI" ,  "crossing_time_in_seconds" :  500 },
{ "trajectory_number" :  '4' ,  "trajectory_type" :  "Sepsis" ,  "crossing_time_in_seconds" :  1000 },
{ "trajectory_number" :  '5' ,  "trajectory_type" :  "Sepsis" ,  "crossing_time_in_seconds" :  1243 },
{ "trajectory_number" :  '6' ,  "trajectory_type" :  "Sepsis" ,  "crossing_time_in_seconds" :  1300 },
{ "trajectory_number" :  '7' ,  "trajectory_type" :  "Pneumonia" ,  "crossing_time_in_seconds" :  2304 },
{ "trajectory_number" :  '8' ,  "trajectory_type" :  "Pneumonia" ,  "crossing_time_in_seconds" :  2305 }
])

df.head

df["crossing_time_in_seconds"].median()

df["crossing_time_in_seconds"].mean()

